version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # Debugger
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 8000
      DB_URL: postgres://postgres@postgres/task_management
    command: yarn start:docker

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: task_management
      POSTGRES_HOST_AUTH_METHOD: trust