version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # Debugger
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    command: yarn start:docker

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    env_file: .env
